In [1]:
import numpy as np

In [2]:
A = np.array([[3, 4, 3], 
[1, 2, 3], 
[4, 2, 1]])

In [3]:
print("Original Matrix A:\n", A)

Original Matrix A:
 [[3 4 3]
 [1 2 3]
 [4 2 1]]


In [4]:
U, D, VT = np.linalg.svd(A)

In [5]:
print("\nMatrix U:\n", U)


Matrix U:
 [[-0.73553325 -0.18392937 -0.65204358]
 [-0.42657919 -0.62196982  0.65664582]
 [-0.52632788  0.76113306  0.37901904]]


In [6]:
print("\nSingular Values D:\n", D)


Singular Values D:
 [7.87764972 2.54031671 0.69958986]


In [7]:
print("\nMatrix VT:\n", VT)


Matrix VT:
 [[-0.60151068 -0.61540527 -0.5093734 ]
 [ 0.73643349 -0.18005275 -0.65210944]
 [ 0.30959751 -0.76737042  0.5615087 ]]


In [8]:
D_matrix = np.zeros((U.shape[0], VT.shape[0])) 
np.fill_diagonal(D_matrix, D)

In [9]:
A_remake = (U @ D_matrix @ VT) 
print("\nReconstructed Matrix (REMAKE):\n", A_remake)


Reconstructed Matrix (REMAKE):
 [[3. 4. 3.]
 [1. 2. 3.]
 [4. 2. 1.]]
